# settings.yaml — Configuration PyRIT pour Gandalf
openai:
  api_key: OPENAI_API_KEY
  model: "gpt-4o-mini"
  temperature: 0.2
  max_tokens: 512
  openai_chat_endpoint: "https://api.openai.com/v1/chat/completions"
