apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: tock-genai
data:
  init.sql: |
    -- Create extension for vector storage
    CREATE EXTENSION IF NOT EXISTS vector;
    
    -- Create langfuse database and user
    CREATE DATABASE langfuse;
    CREATE USER langfuse WITH PASSWORD 'langfuse';
    GRANT ALL PRIVILEGES ON DATABASE langfuse TO langfuse;
    
    -- Create schema for vectors if needed
    \c postgres
    CREATE SCHEMA IF NOT EXISTS vectors;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: tock-genai
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: tock-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tock-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-script
