apiVersion: v1
kind: Service
metadata:
  name: langfuse-server
  namespace: tock-genai
spec:
  selector:
    app: langfuse-server
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer  # Pour exposer Langfuse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-server
  namespace: tock-genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse-server
  template:
    metadata:
      labels:
        app: langfuse-server
    spec:
      containers:
      - name: langfuse-server
        image: langfuse/langfuse:2.95.8
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_DATABASE_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_NEXTAUTH_SECRET
        - name: SALT
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_SALT
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_NEXTAUTH_URL
        - name: TELEMETRY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_TELEMETRY_ENABLED
        - name: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
          valueFrom:
            configMapKeyRef:
              name: tock-config
              key: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
