apiVersion: v1
kind: ResourceQuota
metadata:
  name: tock-genai-quota
  namespace: tock-genai
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage resources
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object count quotas
    pods: "50"
    services: "20"
    secrets: "10"
    configmaps: "10"
    
    # Network resources
    services.loadbalancers: "2"
    services.nodeports: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: tock-genai-limits
  namespace: tock-genai
spec:
  limits:
  # Default limits for containers
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
    
  # Limits for PVCs
  - max:
      storage: "50Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
    
  # Limits for pods
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Pod
